name: Test
on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:
jobs:
  test:
    name: Go
    runs-on: ubuntu-latest
    steps:
      - name: Install go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16.6'

      - id: go-cache-paths
        run: |
          echo "::set-output name=go-build::$(go env GOCACHE)"
          echo "::set-output name=go-mod::$(go env GOMODCACHE)"

      - uses: actions/checkout@v2

      - name: Cache go modules
        uses: actions/cache@v2
        with:
          path: ${{ steps.go-cache-paths.outputs.go-mod }}
          key: ${{ runner.os }}-go-mod-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-mod-

      - name: Cache docker
        uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true

      - name: Pull test docker images
        run: |
          docker pull bigtruedata/gcloud-pubsub-emulator:latest

      - name: Download go modules
        run: go mod download

      - name: Run tests
        run: go test -race -covermode atomic -coverprofile=covprofile ./...

      - name: Send coverage
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: go run github.com/mattn/goveralls -coverprofile=covprofile -service=github
